export const fa = {
  brand: {
    name: "استایلینو",
    descriptor: "فروشگاه مد و پوشاک",
    shortDescription:
      "استایلینو انتخابی گزیده از پوشاک و اکسسوری‌های مدرن است؛ با تمرکز بر کیفیت، فیت دقیق و تجربه خرید لوکس.",
    footerDescription:
      "ما در استایلینو پوشاکی می‌سازیم که با زندگی امروز هماهنگ باشد؛ مینیمال، خوش‌دوخت و ماندگار.",
  },
  common: {
    currency: "تومان",
    backToStore: "بازگشت به فروشگاه",
    backToSignIn: "بازگشت به ورود",
    loading: "در حال بارگذاری...",
    tryAgain: "لطفا دوباره تلاش کنید.",
    optional: "اختیاری",
    required: "ضروری",
  },
  nav: {
    home: "خانه",
    products: "محصولات",
    categories: "دسته‌بندی‌ها",
    about: "درباره ما",
    cart: "سبد خرید",
    account: "حساب کاربری",
  },
  auth: {
    signIn: {
      title: "ورود به حساب",
      subtitle: "برای ادامه خرید، وارد حساب خود شوید.",
      cta: "ورود",
      emailLabel: "ایمیل",
      emailPlaceholder: "نمونه: hello@stylino.com",
      passwordLabel: "رمز عبور",
      passwordPlaceholder: "حداقل ۸ کاراکتر",
      noAccount: "حساب کاربری ندارید؟",
      createAccount: "ثبت‌نام کنید",
      invalidCredentialsTitle: "اطلاعات نادرست است",
      invalidCredentialsDescription: "ایمیل یا رمز عبور اشتباه است.",
      genericErrorTitle: "مشکلی پیش آمد",
      genericErrorDescription: "ورود انجام نشد. لطفا دوباره تلاش کنید.",
    },
    signUp: {
      title: "ساخت حساب جدید",
      subtitle: "با چند قدم کوتاه، حساب خود را بسازید.",
      cta: "ثبت‌نام",
      nameLabel: "نام و نام خانوادگی",
      namePlaceholder: "مثال: الهام موسوی",
      emailLabel: "ایمیل",
      emailPlaceholder: "نمونه: hello@stylino.com",
      passwordLabel: "رمز عبور",
      passwordPlaceholder: "حداقل ۸ کاراکتر",
      phoneLabel: "شماره موبایل",
      phonePlaceholder: "مثال: ۰۹۱۲۳۴۵۶۷۸۹",
      haveAccount: "حساب دارید؟",
      signIn: "وارد شوید",
      successTitle: "حساب شما ساخته شد",
      successDescription: "به استایلینو خوش آمدید. در حال ورود...",
      genericErrorTitle: "ثبت‌نام انجام نشد",
      genericErrorDescription: "مشکلی پیش آمد. لطفا دوباره تلاش کنید.",
      requestError: "امکان ثبت‌نام وجود ندارد.",
    },
    error: {
      heading: "کد خطا",
      actions: {
        signIn: "بازگشت به ورود",
        store: "بازگشت به فروشگاه",
      },
      messages: {
        Configuration: {
          title: "خطای پیکربندی",
          description: "پیکربندی سرویس احراز هویت کامل نیست.",
        },
        AccessDenied: {
          title: "دسترسی محدود",
          description: "شما اجازه ورود به این بخش را ندارید.",
        },
        Verification: {
          title: "خطای اعتبارسنجی",
          description: "لینک تایید معتبر نیست یا منقضی شده است.",
        },
        CredentialsSignin: {
          title: "ورود ناموفق",
          description: "اطلاعات ورود نادرست است.",
        },
        OAuthSignin: {
          title: "خطای اتصال",
          description: "ارتباط با سرویس ورود برقرار نشد.",
        },
        OAuthCallback: {
          title: "خطای بازگشت",
          description: "بازگشت از سرویس ورود با خطا مواجه شد.",
        },
        OAuthCreateAccount: {
          title: "خطا در ساخت حساب",
          description: "امکان ساخت حساب با این روش وجود ندارد.",
        },
        EmailCreateAccount: {
          title: "خطا در ساخت حساب",
          description: "ایمیل معتبر نیست یا قبلا استفاده شده است.",
        },
        Callback: {
          title: "خطای ورود",
          description: "فرآیند ورود کامل نشد.",
        },
        OAuthAccountNotLinked: {
          title: "حساب لینک نشده",
          description: "این ایمیل با روش دیگری ثبت شده است.",
        },
        EmailSignin: {
          title: "خطا در ارسال ایمیل",
          description: "ارسال لینک ورود انجام نشد.",
        },
        SessionRequired: {
          title: "نیاز به ورود",
          description: "برای ادامه باید وارد حساب شوید.",
        },
        Default: {
          title: "خطای ناشناخته",
          description: "مشکلی پیش آمد. لطفا دوباره تلاش کنید.",
        },
      },
    },
  },
  cart: {
    title: "سبد خرید",
    subtitle: "جمع {count} قلم در سبد شما",
    emptyTitle: "سبد خرید شما خالی است",
    emptyDescription:
      "برای شروع خرید، محصولات مورد علاقه‌تان را به سبد اضافه کنید.",
    emptyCta: "مشاهده محصولات",
    summaryTitle: "خلاصه سفارش",
    itemsTotal: "جمع کالاها:",
    shipping: "هزینه ارسال:",
    total: "مجموع پرداختی:",
    checkout: "ادامه خرید و پرداخت",
    continueShopping: "ادامه خرید",
    quantityIncrease: "افزایش تعداد",
    quantityDecrease: "کاهش تعداد",
    removeItem: "حذف از سبد خرید",
    productHeader: "محصول",
    quantityHeader: "تعداد",
    priceHeader: "قیمت",
  },
  checkout: {
    title: "تکمیل خرید",
    subtitle: "اطلاعات ارسال را با دقت وارد کنید.",
    customerInfo: "اطلاعات گیرنده",
    shippingInfo: "جزئیات ارسال",
    nameLabel: "نام و نام خانوادگی",
    phoneLabel: "شماره موبایل",
    provinceLabel: "استان",
    cityLabel: "شهر",
    addressLabel: "آدرس کامل",
    postalLabel: "کد پستی",
    notesLabel: "توضیحات سفارش",
    notesPlaceholder: "اگر نکته‌ای برای ارسال دارید، اینجا بنویسید.",
    postalHint: "کد پستی برای ارسال دقیق ضروری است.",
    submit: "ادامه به پرداخت",
    paymentMethod: "روش پرداخت: زرین‌پال",
    orderSummary: "خلاصه سفارش",
    itemCountSuffix: "قلم",
    errors: {
      createOrder: "ثبت سفارش انجام نشد.",
      requestPayment: "ارتباط با درگاه پرداخت برقرار نشد.",
      generic: "مشکلی پیش آمد. لطفا دوباره تلاش کنید.",
    },
  },
  orders: {
    title: "سفارش‌های من",
    subtitle: "پیگیری سفارش‌ها و وضعیت ارسال",
    emptyTitle: "سفارشی ثبت نشده است",
    emptyDescription: "وقتی سفارشی ثبت کنید، وضعیت آن اینجا نمایش داده می‌شود.",
    orderLabel: "سفارش",
    statusFetchError: "دریافت سفارش‌ها با خطا مواجه شد.",
  },
  price: {
    discountLabel: "تخفیف",
    featuredBadge: "ویژه",
    outOfStock: "ناموجود",
    addToCart: "افزودن به سبد خرید",
    addToWishlist: "افزودن به لیست علاقه‌مندی",
    removeFromWishlist: "حذف از لیست علاقه‌مندی",
    addedToCartTitle: "به سبد خرید اضافه شد",
    addedToCartDescription: "محصول با موفقیت به سبد شما اضافه شد.",
    noVariantTitle: "گزینه‌ای موجود نیست",
    noVariantDescription: "برای این محصول گزینه قابل انتخاب وجود ندارد.",
    outOfStockTitle: "ناموجود",
    outOfStockDescription: "این محصول فعلا موجود نیست.",
    addingToCart: "در حال افزودن...",
  },
  footer: {
    quickLinks: "لینک‌های سریع",
    customerService: "خدمات مشتریان",
    contact: "ارتباط با ما",
    about: "درباره ما",
    contactLink: "تماس با ما",
    terms: "شرایط استفاده",
    faq: "سوالات متداول",
    shipping: "ارسال و تحویل",
    sizeGuide: "راهنمای سایز",
    care: "نگهداری لباس",
    privacy: "حریم خصوصی",
    socialInstagram: "اینستاگرام استایلینو",
    socialEmail: "ایمیل استایلینو",
    address: "تهران، خیابان ولیعصر، پلاک ۲۳",
    phone: "۰۲۱-۸۸۸۸۸۸۸۸",
    email: "info@stylino.ir",
    rights: "تمام حقوق برای استایلینو محفوظ است.",
  },
  store: {
    heroTitle: "استایل شخصی، با امضای شما",
    heroSubtitle:
      "منتخب‌های پوشاک و اکسسوری برای کمدی شیک، مینیمال و همیشه به‌روز.",
    heroSubtle: "طراحی برای سلیقه‌های دقیق و جسور.",
    heroPrimaryCta: "مشاهده کالکشن",
    heroSecondaryCta: "مرور دسته‌بندی‌ها",
    storyTitle: "روایت آتلیه استایلینو",
    storyKicker: "استودیو استایل",
    storyHeadline: "جزئیاتی که استایل را ماندگار می‌کند",
    storySteps: [
      {
        title: "دوخت دقیق برای کمد مدرن",
        body: "فیت‌های خوش‌فرم و پارچه‌های تنفس‌پذیر برای همراهی روزانه.",
        kicker: "مجموعه آتلیه",
        image: "/placeholders/N1.png",
      },
      {
        title: "بافت‌های لایه‌دار و سیلوئت‌های تمیز",
        body: "ترکیبی از بافت نرم و ساختار دقیق برای استایلی متعادل.",
        kicker: "ویرایش فصل",
        image: "/placeholders/N2.png",
      },
      {
        title: "جزئیات هدفمند",
        body: "از دوخت تا یراق، هر بخش با وسواس طراحی شده است.",
        kicker: "امضای برند",
        image: "/placeholders/N3.png",
      },
    ],
    featureCards: [
      {
        title: "منتخب‌های ماندگار",
        body: "انتخاب‌های دقیق برای استایل روزمره و رسمی.",
      },
      {
        title: "ارسال سریع",
        body: "بسته‌بندی حرفه‌ای و تحویل مطمئن در سراسر کشور.",
      },
      {
        title: "تعهد کیفیت",
        body: "پارچه‌های ممتاز، دوخت دقیق و کنترل کیفیت سختگیرانه.",
      },
    ],
    featuredTitle: "محصولات شاخص",
    featuredSubtitle: "چند انتخاب خاص برای ارتقای استایل شما.",
    featuredCta: "مشاهده همه",
    stats: [
      { value: "۲۴۰۰+", label: "مشتری وفادار" },
      { value: "۱۲۰+", label: "کالکشن امضادار" },
      { value: "۴٫۹/۵", label: "میانگین رضایت" },
      { value: "۲۴/۷", label: "پشتیبانی همراه" },
    ],
    finalTitle: "همین امروز استایل‌تان را تازه کنید",
    finalSubtitle: "قطعات محدود و کالکشن‌های فصلی که فقط برای شما چیده شده‌اند.",
    finalCta: "شروع خرید",
  },
  products: {
    title: "مجموعه محصولات",
    subtitle: "با فیلتر و مرتب‌سازی، انتخاب دقیق‌تری داشته باشید.",
    filters: "فیلترها",
    closeFilters: "بستن فیلترها",
    resetFilters: "پاک کردن فیلترها",
    category: "دسته‌بندی",
    priceRange: "بازه قیمت",
    minPrice: "حداقل",
    maxPrice: "حداکثر",
    size: "سایز",
    color: "رنگ",
    colorFilterLabel: "فیلتر رنگ",
    showFilters: "نمایش فیلترها",
    sortLabel: "مرتب‌سازی",
    sortNewest: "جدیدترین",
    sortPriceAsc: "کمترین قیمت",
    sortPriceDesc: "بیشترین قیمت",
    sortNameAsc: "نام: الف تا ی",
    itemsCount: "کالا",
    emptyTitle: "محصولی پیدا نشد",
    emptyDescription: "با تغییر فیلترها نتایج بیشتری ببینید.",
  },
  payment: {
    successTitle: "پرداخت موفق",
    successDescription: "سفارش شما ثبت شد و در حال پردازش است.",
    failedTitle: "پرداخت ناموفق",
    failedDescription: "پرداخت کامل نشد. اگر مبلغی کسر شده، حداکثر تا ۷۲ ساعت بازگشت می‌خورد.",
    orderNumber: "شماره سفارش",
    retryPayment: "تلاش دوباره برای پرداخت",
    backToProducts: "بازگشت به محصولات",
    goToOrders: "مشاهده سفارش‌ها",
  },
  about: {
    badge: "داستان برند ما",
    title: "درباره استایلینو",
    intro:
      "استایلینو از یک ایده ساده شروع شد: ساختن تجربه‌ای که کیفیت، ظرافت و دسترسی را همزمان ارائه دهد.",
    introSecond:
      "ما با انتخاب‌های دقیق، فیت‌های استاندارد و جزئیات درست، پوشاکی می‌سازیم که سال‌ها همراه شما باشد.",
    features: [
      {
        title: "انتخاب دقیق محصولات",
        desc: "هر محصول با دقت از میان بهترین‌ها انتخاب می‌شود.",
      },
      {
        title: "قیمت‌گذاری منصفانه",
        desc: "تعادل بین کیفیت و قیمت برای خرید مطمئن.",
      },
      {
        title: "پرداخت امن",
        desc: "پرداخت آنلاین از طریق درگاه‌های معتبر.",
      },
      {
        title: "پشتیبانی واقعی",
        desc: "همراهی تیم پشتیبانی در تمام مراحل خرید.",
      },
    ],
    ctaTitle: "آماده تغییر استایل هستید؟",
    ctaDescription:
      "همین حالا از جدیدترین کالکشن‌های ما دیدن کنید و استایل منحصر به فرد خود را بسازید.",
    ctaButton: "مشاهده همه محصولات",
    premiumLabel: "انتخاب ممتاز",
  },
  pdp: {
    featuredTag: "انتخاب ویژه",
    stockAvailable: "موجود",
    stockUnavailable: "ناموجود",
    quantity: "تعداد",
    selectVariantHint: "ابتدا سایز و رنگ را انتخاب کنید.",
    addedToCart: "به سبد خرید اضافه شد",
    share: "اشتراک‌گذاری",
    wishlist: "علاقه‌مندی",
    sizeGuide: "راهنمای سایز",
    close: "بستن",
    sizeLabel: "سایز",
    colorLabel: "رنگ",
    stockCount: "عدد موجود",
  },
  orderStatus: {
    pending: "در انتظار بررسی",
    processing: "در حال آماده‌سازی",
    shipped: "ارسال شد",
    delivered: "تحویل شد",
    canceled: "لغو شد",
    returned: "مرجوع شد",
    refunded: "مسترد شد",
    transitionError: (from: string, to: string) =>
      `امکان تغییر وضعیت از «${from}» به «${to}» وجود ندارد.`,
  },
} as const
