export const fa = {
  brand: {
    name: "استایلینو",
    descriptor: "فشن لوکس زنانه",
    shortDescription:
      "استایلینو بوتیک آنلاین مد زنانه با انتخابی curated از لباس، کیف و اکسسوری برای استایل‌های روز و مراسم است.",
    footerDescription:
      "ما در استایلینو با تمرکز بر کیفیت، تناسب و زیبایی، تجربه‌ای لوکس از خرید آنلاین مد زنانه را ارائه می‌کنیم.",
  },
  common: {
    currency: "تومان",
    backToStore: "بازگشت به فروشگاه",
    backToSignIn: "بازگشت به ورود",
    loading: "در حال بارگذاری...",
    tryAgain: "لطفا دوباره تلاش کنید.",
    optional: "اختیاری",
    required: "الزامی",
  },
  nav: {
    home: "خانه",
    products: "محصولات",
    categories: "دسته‌بندی‌ها",
    about: "درباره ما",
    cart: "سبد خرید",
    account: "حساب کاربری",
  },
  auth: {
    signIn: {
      title: "ورود به حساب",
      subtitle: "برای دسترسی به حساب خود وارد شوید یا ثبت‌نام کنید.",
      cta: "ورود",
      emailLabel: "ایمیل",
      emailPlaceholder: "hello@stylino.com",
      passwordLabel: "رمز عبور",
      passwordPlaceholder: "حداقل ۸ کاراکتر",
      noAccount: "حساب کاربری ندارید؟",
      createAccount: "ثبت‌نام کنید",
      invalidCredentialsTitle: "ورود ناموفق",
      invalidCredentialsDescription: "ایمیل یا رمز عبور اشتباه است.",
      genericErrorTitle: "خطای غیرمنتظره",
      genericErrorDescription: "مشکلی رخ داد. لطفا دوباره تلاش کنید.",
    },
    signUp: {
      title: "ساخت حساب کاربری",
      subtitle: "ثبت‌نام کنید و خریدهای لوکس خود را آغاز کنید.",
      cta: "ثبت‌نام",
      nameLabel: "نام و نام خانوادگی",
      namePlaceholder: "مثال: نازنین احمدی",
      emailLabel: "ایمیل",
      emailPlaceholder: "hello@stylino.com",
      passwordLabel: "رمز عبور",
      passwordPlaceholder: "حداقل ۸ کاراکتر",
      phoneLabel: "شماره موبایل",
      phonePlaceholder: "مثال: 09123456789",
      haveAccount: "حساب کاربری دارید؟",
      signIn: "وارد شوید",
      successTitle: "ثبت‌نام موفق",
      successDescription: "حساب شما ساخته شد. در حال ورود...",
      genericErrorTitle: "ثبت‌نام ناموفق",
      genericErrorDescription: "مشکلی رخ داد. لطفا دوباره تلاش کنید.",
      requestError: "ثبت‌نام انجام نشد. دوباره تلاش کنید.",
    },
    error: {
      heading: "خطای ورود",
      actions: {
        signIn: "بازگشت به ورود",
        store: "بازگشت به فروشگاه",
      },
      messages: {
        Configuration: {
          title: "پیکربندی نادرست",
          description: "تنظیمات ورود مشکل دارد. لطفا با پشتیبانی تماس بگیرید.",
        },
        AccessDenied: {
          title: "دسترسی غیرمجاز",
          description: "اجازه دسترسی به این بخش را ندارید.",
        },
        Verification: {
          title: "خطای تایید",
          description: "لینک تایید نامعتبر یا منقضی شده است.",
        },
        CredentialsSignin: {
          title: "ورود ناموفق",
          description: "ایمیل یا رمز عبور اشتباه است.",
        },
        OAuthSignin: {
          title: "ورود ناموفق",
          description: "ورود با سرویس خارجی انجام نشد.",
        },
        OAuthCallback: {
          title: "خطای بازگشت",
          description: "مشکلی در بازگشت از سرویس ورود رخ داد.",
        },
        OAuthCreateAccount: {
          title: "ایجاد حساب ناموفق",
          description: "ایجاد حساب از طریق سرویس خارجی انجام نشد.",
        },
        EmailCreateAccount: {
          title: "ایجاد حساب ناموفق",
          description: "ایمیل معتبر نیست یا قبلا استفاده شده است.",
        },
        Callback: {
          title: "خطای ورود",
          description: "در فرآیند ورود مشکلی رخ داد.",
        },
        OAuthAccountNotLinked: {
          title: "حساب متصل نیست",
          description: "برای ادامه، با همان روش قبلی وارد شوید.",
        },
        EmailSignin: {
          title: "ورود با ایمیل ناموفق",
          description: "لینک ورود نامعتبر یا منقضی شده است.",
        },
        SessionRequired: {
          title: "نیاز به ورود",
          description: "برای ادامه باید وارد حساب خود شوید.",
        },
        Default: {
          title: "خطای ناشناخته",
          description: "مشکلی رخ داد. لطفا دوباره تلاش کنید.",
        },
      },
    },
  },
  cart: {
    title: "سبد خرید",
    subtitle: "شما {count} محصول در سبد دارید.",
    emptyTitle: "سبد خرید خالی است",
    emptyDescription:
      "محصولی در سبد شما نیست. از فروشگاه دیدن کنید و انتخاب خود را انجام دهید.",
    emptyCta: "مشاهده محصولات",
    summaryTitle: "خلاصه سفارش",
    itemsTotal: "جمع اقلام:",
    shipping: "هزینه ارسال:",
    total: "جمع کل:",
    checkout: "ادامه به پرداخت",
    continueShopping: "ادامه خرید",
    quantityIncrease: "افزایش تعداد",
    quantityDecrease: "کاهش تعداد",
    removeItem: "حذف از سبد خرید",
    productHeader: "محصول",
    quantityHeader: "تعداد",
    priceHeader: "قیمت",
  },
  checkout: {
    title: "پرداخت",
    subtitle: "اطلاعات ارسال خود را وارد کنید.",
    customerInfo: "اطلاعات گیرنده",
    shippingInfo: "اطلاعات ارسال",
    nameLabel: "نام و نام خانوادگی",
    phoneLabel: "شماره موبایل",
    provinceLabel: "استان",
    cityLabel: "شهر",
    addressLabel: "آدرس",
    postalLabel: "کد پستی",
    notesLabel: "یادداشت سفارش",
    notesPlaceholder: "اگر توضیحی دارید اینجا بنویسید.",
    postalHint: "کد پستی ۱۰ رقمی را وارد کنید.",
    submit: "پرداخت و ثبت سفارش",
    paymentMethod: "روش پرداخت: آنلاین",
    orderSummary: "خلاصه سفارش",
    itemCountSuffix: "عدد",
    errors: {
      createOrder: "ثبت سفارش انجام نشد.",
      requestPayment: "خطا در اتصال به درگاه پرداخت.",
      generic: "مشکلی رخ داد. لطفا دوباره تلاش کنید.",
    },
  },
  orders: {
    title: "سفارش‌های شما",
    subtitle: "لیست سفارش‌های ثبت‌شده شما.",
    emptyTitle: "سفارشی ثبت نشده",
    emptyDescription: "هنوز سفارشی ندارید. از محصولات ما دیدن کنید.",
    orderLabel: "سفارش",
    statusFetchError: "دریافت وضعیت سفارش انجام نشد.",
  },
  price: {
    discountLabel: "تخفیف",
    featuredBadge: "ویژه",
    outOfStock: "ناموجود",
    addToCart: "افزودن به سبد خرید",
    addToWishlist: "افزودن به علاقه‌مندی‌ها",
    removeFromWishlist: "حذف از علاقه‌مندی‌ها",
    addedToCartTitle: "به سبد خرید اضافه شد",
    addedToCartDescription: "این محصول به سبد خرید شما اضافه شد.",
    noVariantTitle: "انتخاب مشخصات لازم است",
    noVariantDescription: "لطفاً سایز و رنگ موردنظر را انتخاب کنید.",
    outOfStockTitle: "ناموجود",
    outOfStockDescription: "این محصول در حال حاضر موجود نیست.",
    addingToCart: "در حال افزودن...",
  },
  footer: {
    quickLinks: "لینک‌های سریع",
    customerService: "خدمات مشتریان",
    contact: "راه‌های ارتباطی",
    about: "درباره ما",
    contactLink: "تماس با ما",
    terms: "قوانین و شرایط",
    faq: "سوالات متداول",
    shipping: "ارسال و بازگشت",
    sizeGuide: "راهنمای سایز",
    care: "راهنمای نگهداری",
    privacy: "حریم خصوصی",
    socialInstagram: "اینستاگرام",
    socialEmail: "ایمیل",
    address: "تهران، خیابان ولیعصر، پلاک ۱۲۳",
    phone: "021-12345678",
    email: "info@stylino.ir",
    rights: "تمام حقوق برای استایلینو محفوظ است.",
  },
  store: {
    heroTitle: "استایلینو، الهام از ظرافت زنانه",
    heroSubtitle:
      "منتخبی از استایل‌های لوکس و مدرن برای لحظه‌های خاص و روزمره.",
    heroSubtle: "ظرافت در جزئیات، کیفیت در انتخاب.",
    heroPrimaryCta: "خرید محصولات",
    heroSecondaryCta: "مشاهده دسته‌بندی‌ها",
    storyTitle: "قصه استایلینو",
    storyKicker: "فلسفه برند",
    storyHeadline: "سه گام تا استایل لوکس و ماندگار",
    storySteps: [
      {
        title: "انتخاب دقیق برای ظاهری بی‌نقص",
        body: "هر محصول از میان برندها و طرح‌های منتخب انتخاب می‌شود تا استایل شما خاص و متفاوت باشد.",
        kicker: "انتخاب هوشمند",
        image: "/placeholders/N1.png",
      },
      {
        title: "کیفیت در بافت، ظرافت در دوخت",
        body: "جزئیات دقیق و کیفیت ساخت بالا، امضای همیشگی محصولات ماست.",
        kicker: "کیفیت برتر",
        image: "/placeholders/N2.png",
      },
      {
        title: "تجربه‌ای آرام از خرید لوکس",
        body: "از انتخاب تا تحویل، همه چیز ساده و شفاف طراحی شده است.",
        kicker: "تجربه دلنشین",
        image: "/placeholders/N3.png",
      },
    ],
    featureCards: [
      {
        title: "منتخب لوکس",
        body: "کالکشن‌های محدود و خاص با کیفیت ممتاز.",
      },
      {
        title: "ارسال سریع",
        body: "تحویل مطمئن و سریع به سراسر ایران.",
      },
      {
        title: "پشتیبانی اختصاصی",
        body: "همراهی و پاسخ‌گویی پیش و پس از خرید.",
      },
    ],
    featuredTitle: "منتخب این فصل",
    featuredSubtitle: "محصولات ویژه با استایل امضا شده استایلینو.",
    featuredCta: "مشاهده همه",
    stats: [
      { value: "۱۲k+", label: "مشتری وفادار" },
      { value: "۳k+", label: "محصول منتخب" },
      { value: "۴.۹/۵", label: "امتیاز تجربه" },
      { value: "۲۴/۷", label: "پشتیبانی" },
    ],
    finalTitle: "استایل خود را از همین امروز بسازید",
    finalSubtitle: "با محصولات منتخب ما، تجربه‌ای لوکس و متفاوت داشته باشید.",
    finalCta: "شروع خرید",
  },
  products: {
    title: "مجموعه محصولات",
    subtitle: "منتخب‌های لوکس با کیفیت و طراحی منحصربه‌فرد.",
    filters: "فیلترها",
    closeFilters: "بستن فیلترها",
    resetFilters: "بازنشانی فیلترها",
    category: "دسته‌بندی",
    priceRange: "بازه قیمت",
    minPrice: "حداقل",
    maxPrice: "حداکثر",
    size: "سایز",
    color: "رنگ",
    colorFilterLabel: "فیلتر رنگ",
    showFilters: "نمایش فیلترها",
    sortLabel: "مرتب‌سازی",
    sortNewest: "جدیدترین",
    sortPriceAsc: "قیمت: کم به زیاد",
    sortPriceDesc: "قیمت: زیاد به کم",
    sortNameAsc: "نام: الف تا ی",
    itemsCount: "تعداد",
    emptyTitle: "محصولی یافت نشد",
    emptyDescription: "فیلترهای خود را تغییر دهید یا دوباره تلاش کنید.",
  },
  payment: {
    successTitle: "پرداخت موفق",
    successDescription: "سفارش شما ثبت شد و در حال پردازش است.",
    failedTitle: "پرداخت ناموفق",
    failedDescription: "پرداخت انجام نشد. لطفا دوباره تلاش کنید.",
    orderNumber: "شماره سفارش",
    retryPayment: "تلاش دوباره",
    backToProducts: "بازگشت به محصولات",
    goToOrders: "مشاهده سفارش‌ها",
  },
  about: {
    badge: "داستان برند",
    title: "درباره استایلینو",
    intro:
      "استایلینو با تمرکز بر کیفیت و زیبایی، تجربه‌ای لوکس از خرید مد زنانه ارائه می‌کند.",
    introSecond:
      "ما با انتخاب دقیق محصولات و توجه به جزئیات، همراه شما در ساخت استایلی متفاوت هستیم.",
    features: [
      {
        title: "منتخب باکیفیت",
        desc: "هر محصول با دقت و استاندارد بالا انتخاب می‌شود.",
      },
      {
        title: "قیمت شفاف",
        desc: "قیمت‌گذاری منصفانه و روشن برای خریدی مطمئن.",
      },
      {
        title: "پرداخت امن",
        desc: "درگاه پرداخت امن و معتبر برای آرامش خاطر شما.",
      },
      {
        title: "ارسال سریع",
        desc: "ارسال سریع و بسته‌بندی شیک برای تجربه‌ای خاص.",
      },
    ],
    ctaTitle: "به دنیای استایلینو خوش آمدید",
    ctaDescription:
      "با ما همراه شوید و استایل خود را به سطحی جدید برسانید.",
    ctaButton: "مشاهده محصولات",
    premiumLabel: "لوکس و ویژه",
  },
  pdp: {
    featuredTag: "منتخب",
    stockAvailable: "موجود",
    stockUnavailable: "ناموجود",
    quantity: "تعداد",
    selectVariantHint: "برای خرید، سایز و رنگ را انتخاب کنید.",
    addedToCart: "به سبد خرید اضافه شد",
    share: "اشتراک‌گذاری",
    wishlist: "علاقه‌مندی‌ها",
    sizeGuide: "راهنمای سایز",
    close: "بستن",
    sizeLabel: "سایز",
    colorLabel: "رنگ",
    stockCount: "عدد موجود",
  },
  orderStatus: {
    pending: "در انتظار تایید",
    processing: "در حال پردازش",
    shipped: "ارسال شده",
    delivered: "تحویل شده",
    canceled: "لغو شده",
    returned: "مرجوع شده",
    refunded: "بازگشت وجه",
    transitionError: (from: string, to: string) =>
      `تغییر وضعیت از «${from}» به «${to}» ممکن نیست.`,
  },
} as const
